networks:
  dev:

services:
  db:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - './database:/var/lib/postgresql/data'
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d taskmaster" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "template"
    networks:
      - dev

  backend:
    build:
      context: ./server
    networks:
      - dev
    depends_on:
      frontend:
        condition: service_started
      db:
        condition: service_healthy


  frontend:
    build:
      context: ./client/TaskMaster
    networks:
      - dev
    depends_on:
      - db